author: Rachel Wong
email: wongrawr@gmail.com
description: Cognitive Psychology graduate student at Florida Atlantic University.
# social links
github_username: rachelw0ng

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
