title: Projects
author: Rachel Wong
email: wongrawr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
# social links
github_username:  rachelw0ng

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
